# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KDAlbums' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Albums
  # add pods for desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods
  #pod 'Firebase/AppDistribution'
  
end
